### ISSUE TITLE
Allowing Non-female preseting characters?

### ISSUE THREAD

**Issue by laynH** [laynH/Anime-Girls-Holding-Programming-Books#73]
https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/pull/70#issue-281847306

Someone submitted this picture of Mista holding SICP in a pull request. While Mista is holding a programming book he isn't really a girl. Up to now I've only been allowing characters that are either canonically female or at least look female(acceptions were made for a ceiling lamp) but Mista doesn't really fit in either category. 

I want to keep this repo cute and CS related, and while I admit that male characters can be cute and can hold CS related books I'm not sure if allowing them to be added like girls are added would be the best thing for this repos aesthetic. 

Right now I have three potential solutions

1. Allow them to be added just like girls are added

2. Create a directory in this repo for boys that would serve as sort of a sub-repo that has the same rules about categorization and file names that the rest of the repo has. (If we went this route I'd take a pretty hard stance on female presenting characters being girls)

3. Create a separate repo for boys.

Im making this issue to ask people who contribute to this repo to give input on what they think the decision should be.

**Comment by Asday** [comment]
Boys are icky.

I know JJBA is somewhat of a silly show, though - could Mista, in universe, blend in with ladies?  If so, then it makes sense to let him in.

**Comment by reaysawa** [comment]
It's only a misgiving because the girls are usually enacting a reaction or pose drawn from a depiction of a female character (whatever the definition of that may be for the anime industry). Example: [Uiharu](https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/blob/master/C%2B%2B/Uiharu_Kazari_Modern_CPP_Design%20.jpg)'s body expression here is usually **not** associated with the male persona in anime characters.

In contrast, the photo in that PR can't be thought to follow the same notion, not in the facial expression, not in the pose, or... In any way, really.

Following that thought, I think creating another repository would make most sense. IMO the main novelty of this repository is the theme around girl(ish) characters holding books, not just straight up memeing. Plus there's no extra burden in having two separate places.

**Comment by bucket3432** [comment]
+1 to a separate repo. It would be great to have Kyon and Oreki holding programming books, but they don't belong here.

**Comment by shekeru** [comment]
`1` would be the most convenient while they're still few, but after then perhaps maybe subfolders of `[males]` in their appropriate category folders, rather than a separate folder acting as a subrepo, would in my opinion be a good middle ground between ordering, and convince. I need more memes brah.

**Comment by bucket3432** [comment]
But if we have male subfolders, that means I can't just point my image viewer to this repo and get exactly and only what the repo promises (i.e. anime girls holding programming books). Non-obvious traps like what we have here I think are okay here because you initially think they're girls, but when you realize otherwise, it's "funny", especially if you then show it to an unsuspecting friend.

Besides, repos are cheap. If you wanted to, you could create a repo with two submodules, one that points to this one and one that points to the male one, and then you'd have them all in the same repo (sort of).

**Comment by Asday** [comment]
>Besides, repos are cheap

Which reminds me, how close are we to the filesize limit of the repo?

**Comment by bucket3432** [comment]
Nowhere close. Repos have a [hard limit at 100 GB](https://help.github.com/en/articles/what-is-my-disk-quota#file-and-repository-size-limitations), but you get a warning once you reach 75 GB. This repo is currently only 88 MB.

**Comment by Asday** [comment]
Aah much appreciated.  My dumb ass remembered

>In addition, we place a strict limit of files exceeding 100 MB in size

applying to the repo as a whole, somehow.

**Comment by bucket3432** [comment]
From what I recall, I think we've settled on not having non-female presenting characters in this repo. Does the [Konobi art club president](https://github.com/laynH/Anime-Girls-Holding-Programming-Books/blob/master/SICP/Konobi_President_Hiding_SICP.png) get grandfathered in?

**Comment by Asday** [comment]
I vote "no", but also should probably be a separate issue.

**Comment by bucket3432** [comment]
You're right, my bad. I've created #101 to propose the removal. We can discuss the specific matters there.
